title: OpenDevice
description: Open IoT (Internet Of Things) Platform and Framework.
author: Ricardo JL Rufino
organization: CriativaSoft
blog_path: /news
# Disable interpolate after upgrading to Awestruct 0.5.4
#interpolate: false
# FIXME timezone will need to be specified per post for a global team
local_tz: America/Bahia
disqus: opendevice
disqus_generate_id: true
disqus_developer: true
haml:
  :ugly: true
asciidoctor:
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    icons: 'font'
    sectanchors: ''
    linkattrs: ''
    #source-highlighter: highlight.js
    source-highlighter: coderay
    'prewrap!': ''
# if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    deploy: nil
  staging:
    deploy: nil
  production:
    base_url: http://opendevice.criativasoft.com.br
    disqus_developer: false
    google_analytics: UA-52975804-2
    compass_output_style: :compressed
    # TODO enable minify once we verify it's working as expected
    #minify: true
    deploy:
      host: github_pages
      branch: gh-pages
