= Download
:page-layout: base
:toc:
:sources: https://github.com/OpenDevice
:issues-ref: https://github.com/OpenDevice/issues
:maven-repo-ref: http://mvnrepository.com/artifact/br.com.criativasoft.opendevice
:docs-ref: link:/docs
:table-caption!:
:language: java
:font-awesome-url: http://fortawesome.github.io/Font-Awesome/
:license: https://raw.githubusercontent.com/OpenDevice/master/license/license.txt

== Downloads


Before using OpenDevice you will need as a minimum a Java Development Kit (JDK) installed version 1.6 or above. Download the appropriate JDK for your operating system, run the installer, and then set up an environment variable called JAVA_HOME pointing to the location of this installation.

NOTE: End-User Download section is not active, goto https://opendevice.atlassian.net/wiki/display/DOC[Docs^]. I'll show you how to use 'Developer Components' and APIs.

|===
|Name |Download |Docs

|Middleware (Server)
|not active
|Guide

|Android App
|not active
|Guide

|Firmware 
|not active
|Guide
|===



// References:
//https://github.com/xively/xively_arduino
//https://github.com/xively/XivelyAndroid
//https://xively.com/dev/tutorials/pi/
//https://xively.com/dev/tutorials/arduino_wi-fi/
//https://xively.com/dev/hardware/

// {asterisk} TODO: É preciso colocar informações de como instalar cada um e executar...


== Developer Components and Plugins

Most components in OpenDevice is developed in JAVA and is published to Maven Central.


[source,xml]
.pom.xml
----
<repositories>
	<repository>
		<id>oss.sonatype.org</id>
		<url>https://oss.sonatype.org/content/repositories/releases</url>
	</repository>
	<repository>
		<id>oss.sonatype.org-snapshot</id>
		<url>https://oss.sonatype.org/content/repositories/snapshots</url>
	</repository>
</repositories>


<dependencies>
	<dependency>
		<groupId>br.com.criativasoft.opendevice</groupId>
		<artifactId>opendevice-connection-stream</artifactId>
		<version>${opendevice-version}</version>
	</dependency>

	<dependency>
		<groupId>br.com.criativasoft.opendevice</groupId>
		<artifactId>opendevice-core</artifactId>
		<version>${opendevice-version}</version>
	</dependency>

	<dependency>
		<groupId>br.com.criativasoft.opendevice</groupId>
		<artifactId>opendevice-rest-ws-server</artifactId>
		<version>${opendevice-version}</version>
	</dependency>	
</dependencies>
----

NOTE: Replace ${opendevice-version} to last version found in: https://oss.sonatype.org/#nexus-search;quick~opendevice[repository^]

////

|===
|Name |Info |Download
|Rest  WebSocket Client
|Android and Desktop compatible
|link

|C/C++ Lib
|Arduino / Stelaris Lib
|link

|JavaScript API
|Based no Atmosphere and Angular.JS
|link

|Samples
|
|Sample Dir
|===
////



== Getting Started

For details of how to develop using OpenDevice APIs, recommend reading the documentation specific to each component (the links pointing in the downloads section) and check the sample projects. However you can start with a more general guide

* https://opendevice.atlassian.net/wiki/display/DOC[Getting Started & Docs]

== Sources

The OpenDevice is available on GitHub and includes the complete stack to build solutions for the "Internet of Things"

* {sources}[GitHub Repository for OpenDevice] 

== License

Copyright (c) 2013-2014 CriativaSoft. Free use of this software is granted under the terms of the Eclipse Public License v1.0.
See the {license}[LICENSE] file for details.





